apiVersion: v1
data:
  DBHOST: "postgres-postgresql.pgdatabase.svc.cluster.local"
  DBPORT: "5432"
  DBNAME: "vecsearch"
  PORT: "5002"
  DIALECT: "bq"
  REDIS_HOST: "redis-stack-server.redis-stack.svc.cluster.local"
  S3_ENDPOINT: "minio.minio.svc.cluster.local"
  S3_PORT: "9000"
  FILE_BUCKET: "vecsearch"
kind: ConfigMap
metadata:
  name: "{{ .Values.app }}"
  namespace: "{{ .Values.namespace }}"
