apiVersion: v1
data:
  DBHOST: "postgres-postgresql.pgdatabase.svc.cluster.local"
  DBPORT: "5432"
  DBNAME: "vecsearch"
  PORT: "6010"
  DIALECT: "bq"
  # PROJECT_ID: "anaml-dev-nonprod"
  # KEY_FILENAME: "/usr/src/app/***REMOVED***"
  PROJECT_ID: "anaml-demo-nonprod"
  KEY_FILENAME: "/usr/src/app/***REMOVED***"
kind: ConfigMap
metadata:
  name: vecsearch
  namespace: nudge
