apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
stringData:
  DBUSER: "{{ .Values.db.user }}"
  DBPASS: "{{ .Values.db.pass }}"
  AWS_ACCESS_KEY: "{{ .Values.minio.access_key }}"
  AWS_SECRET_KEY: "{{ .Values.minio.secret_key }}"
  REDIS_PASSWORD: "{{ .Values.redis.password }}"
